name: Deploy to Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/testRepo:${{ github.sha }}

      - name: Deploy to Docker
        uses: docker/deploy-action@v1
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/testRepo:${{ github.sha }}
          name: testRepo
          ports: 80:80